import { useThemeStore } from './store/themeStore';

export type ThemePalette = { [key: string]: string; isDark: boolean };

export function useTheme(): ThemePalette & { isDark: boolean } {
  const theme = useThemeStore(s => s.theme);
  const isDark = theme === 'dark';
  return {
    isDark,
    bg: 'var(--m-bg)',
    surface: 'var(--m-surface)',
    surfaceOpaque: 'var(--m-surface-opaque)',
    surfaceElevated: 'var(--m-surface-elevated)',
    surfaceHover: 'var(--m-surface-hover)',
    border: 'var(--m-border)',
    borderSubtle: 'var(--m-border-subtle)',
    textPrimary: 'var(--m-text-primary)',
    textSecondary: 'var(--m-text-secondary)',
    textMuted: 'var(--m-text-muted)',
    textDim: 'var(--m-text-dim)',
    textFaint: 'var(--m-text-faint)',
    inputBg: 'var(--m-input-bg)',
    badgeBg: 'var(--m-badge-bg)',
    dotGrid: 'var(--m-dot-grid)',
    minimapBg: 'var(--m-bg)',
    minimapMask: isDark ? 'oklch(0.15 0.005 280 / 0.8)' : 'oklch(0.95 0.005 260 / 0.8)',
    minimapNode: 'var(--m-surface-elevated)',
    controlsBg: 'var(--m-surface-opaque)',
    controlsBorder: 'var(--m-border)',
    tileActiveBg: 'var(--m-surface-elevated)',
    tileHoverBg: 'var(--m-surface-hover)',
    tileBg: 'var(--m-surface-opaque)',
    tileBorderHover: isDark ? 'oklch(0.32 0.005 280)' : 'oklch(0.75 0.005 260)',
    agentBg: isDark ? 'oklch(0.16 0.01 50)' : 'oklch(0.97 0.005 50)',
    agentBorder: isDark ? 'oklch(0.24 0.01 50)' : 'oklch(0.88 0.005 50)',
    agentLabel: isDark ? 'oklch(0.60 0.02 50)' : 'oklch(0.45 0.02 50)',
    agentMeta: isDark ? 'oklch(0.48 0.02 50)' : 'oklch(0.55 0.02 50)',
    agentArrow: isDark ? 'oklch(0.48 0.02 50)' : 'oklch(0.55 0.02 50)',
    agentLineNum: isDark ? 'oklch(0.24 0.01 50)' : 'oklch(0.85 0.005 50)',
    agentText: isDark ? 'oklch(0.55 0.02 50)' : 'oklch(0.50 0.02 50)',
    tokenLabel: 'var(--m-text-muted)',
    tokenDivider: 'var(--m-text-secondary)',
    tokenTrackBg: 'var(--m-surface-elevated)',
    jackRingBase: isDark ? 'oklch(0.10 0 0)' : 'oklch(0.92 0.005 260)',
    jackLabelOnRing: 'var(--m-text-muted)',
    jackLabelBeside: 'var(--m-text-dim)',
    cableShadow: isDark ? 'oklch(0 0 0 / 0.4)' : 'oklch(0 0 0 / 0.12)',
    cableHighlight: isDark ? 'oklch(1 0 0 / 0.06)' : 'oklch(1 0 0 / 0.3)',
    responseBg: 'var(--m-surface)',
    responseText: 'var(--m-text-secondary)',
    statusSuccess: 'var(--m-success)',
    statusError: 'var(--m-error)',
    statusWarning: 'var(--m-warning)',
    statusInfo: 'var(--m-info)',
    statusSuccessBg: 'var(--m-success-bg)',
    statusErrorBg: 'var(--m-error-bg)',
    statusWarningBg: 'var(--m-warning-bg)',
    statusSuccessGlow: 'var(--m-success-glow)',
    statusErrorGlow: 'var(--m-error-glow)',
    statusWarningGlow: 'var(--m-warning-glow)',
    cableSkills: 'var(--m-cable-skills)',
    cableMcp: 'var(--m-cable-mcp)',
    cableKnowledge: 'var(--m-cable-knowledge)',
  };
}
